<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Архитектура");
$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH . "/css/architecture.min.css?v=1", true);
?><? $APPLICATION->IncludeComponent(
	"itip:news.ajax", 
	"architecture_ajax_v1", 
	array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "NAME",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000",
		"CACHE_TYPE" => "N",
		"CHECK_DATES" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "PROJECT_TYPE",
			1 => "PROJECT_GEO",
			2 => "PROJECT_STATUS",
			3 => "PROJECT_YEAR",
			4 => "PROJECT_AUTORS",
			5 => "PROJECT_ADV_DESCRIPTION_EN",
			6 => "PROJECT_ADV_DESCRIPTION_RU",
			7 => "PROJECT_GRID_TITLE_EN",
			8 => "PROJECT_GRID_TITLE_RU",
			9 => "PROJECT_SLIDER_TITLE_EN",
			10 => "PROJECT_SLIDER_TITLE_RU",
			11 => "PROJECT_LATLONG",
			12 => "PROJECT_LOCATION_EN",
			13 => "PROJECT_LOCATION_RU",
			14 => "PROJECT_MAIN_TITLE_EN",
			15 => "PROJECT_MAIN_TITLE_RU",
			16 => "PROJECT_FULL_AREA",
			17 => "PROJECT_MAIN_DESCRIPTION_EN",
			18 => "PROJECT_MAIN_DESCRIPTION_RU",
			19 => "PROJECT_DATE_DEV_EN",
			20 => "PROJECT_DATE_DEV_RU",
			21 => "PROJECT_CO_AUTHORS_EN",
			22 => "PROJECT_CO_AUTHORS_RU",
			23 => "PROJECT_SLIDER_MIDLE",
			24 => "PROJECT_PHOTO_GRID",
			25 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"FILTER_PROPERTY_CODE" => array(
			0 => "PROJECT_TYPE",
			1 => "PROJECT_GEO",
			2 => "PROJECT_STATUS",
			3 => "PROJECT_YEAR",
			4 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "2",
		"IBLOCK_TYPE" => "projects",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "PROJECT_MAIN_TITLE_RU",
			2 => "PROJECT_MAIN_TITLE_EN",
			3 => "PROJECT_DATE_DEV_RU",
			4 => "PROJECT_DATE_DEV_EN",
			5 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "PROJECT_TYPE",
			1 => "PROJECT_GEO",
			2 => "PROJECT_STATUS",
			3 => "PROJECT_YEAR",
			4 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "11",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "ask",
		"PAGER_TITLE" => "Новости компании",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/projects/architecture/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "ACTIVE_FROM",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "architecture_ajax_v1",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
); ?>
<script src="<?= SITE_TEMPLATE_PATH ?>/js/lazyLoad.min.js"></script>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>